from __future__ import print_function
import os, site

#package = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'packages')
package = os.path.dirname(os.path.abspath(__file__))
print(package)

pathspec = r"""
# Generated by Crypto-History's installer (install_locally.py)
# In the lines below, list the paths where Python should look for
# supplied modules, one directory per line.
#
# If a directory does not exist when Python is started, it will be ignored.
%s
""" % package

print("Adding path:", package)

usp = site.getusersitepackages()
if not os.path.exists(usp):
    os.makedirs(usp)
uspfile = os.path.join(usp, 'crypto-history.pth')
open(uspfile, 'w').write(pathspec)
print('Wrote to ' + uspfile)
print("Crypto-history package installed successfully!")
